In [3]:
from rlhf.idpg import IDPGPromptGenerator
import torch


In [4]:
d = 10
t = 5
m = 3

pg = IDPGPromptGenerator(d, m, t)

In [6]:
x = torch.rand(d)
y = pg(x)
y

[tensor([ 0.1631, -0.4359,  0.0722,  0.1275, -0.2227, -0.1458,  0.0162, -0.2365,
         -0.1709,  0.3248], grad_fn=<ViewBackward0>),
 tensor([ 0.1486, -0.4718, -0.0700,  0.4408, -0.0450, -0.1649,  0.0579,  0.2615,
          0.4335, -0.4168], grad_fn=<ViewBackward0>),
 tensor([-0.3492,  0.2165, -0.4551,  0.5103,  0.1816,  0.0853, -0.3421, -0.2208,
          0.1167, -0.2940], grad_fn=<ViewBackward0>),
 tensor([ 0.1305,  0.0850,  0.2129,  0.5201,  0.2160,  0.2339,  0.2627, -0.0876,
          0.5306, -0.2927], grad_fn=<ViewBackward0>),
 tensor([ 0.2104, -0.5195, -0.4981, -0.0587,  0.0844, -0.3291, -0.2922,  0.0584,
          0.3818, -0.0329], grad_fn=<ViewBackward0>)]